rootPageId: 1
websiteTitle: 'Physiozeit Penzberg'
baseVariants:
  - base: 'http://physiozeit-penzberg.local'
    condition: 'applicationContext == "Development"'
  - base: 'https://www.physiozeit-penzberg.de'
    condition: 'applicationContext == "Production"'
languages:
  -
    title: Deutsch
    enabled: true
    languageId: 0
    base: /
    typo3Language: de
    locale: de_DE.UTF-8
    iso-639-1: de
    navigationTitle: Deutsch
    hreflang: de
    direction: ''
    flag: de
errorHandling:
  -
    errorCode: '404'
    errorHandler: Page
    errorContentSource: 't3://page?uid=47'
routes:
  - route: sitemap.xml
    type: uri
    source: 't3://page?type=1533906435'
  -
    route: robots.txt
    type: staticText
    content: "User-agent: *\r\nDisallow: /typo3/\r\nDisallow: /vendor/\r\nDisallow: /typo3_src/\r\nSitemap: https://www.physiozeit-penzberg.de/sitemap.xml"